[phases.setup]
nixPkgs = ['nodejs_22']

[phases.install]
cmds = [
    'cp -n .env.example .env || true',
    'composer install --optimize-autoloader --no-dev --no-interaction',
    'npm ci'
]

[phases.build]
cmds = [
    'npm run build'
]

[start]
cmd = 'bash start.sh'
